version: '3.8'
services:

  db:
    image: postgres:15.0-alpine
    container_name: database
    volumes:
    - dbdata:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ../.env

  app:
    build:
      context: ../
    container_name: app
    command: ['/app/infra/script.sh']
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  dbdata:
