"""create table zuzublik

Revision ID: 986004cbed66
Revises: 
Create Date: 2023-04-15 13:45:38.955988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986004cbed66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zuzublik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('xpath', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zuzublik')
    # ### end Alembic commands ###
